### PR TITLE
Create harbour-exporter-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

### CODE REVIEW

**Comment by GoAlexander** [comment]
Thanks for contribution!

**Comment by GoAlexander** [comment]
Thanks for contribution!

**Comment by eson57** [comment]
No problem! Line 52, 60 does not translate, btw...

screen_20161123_001

**Comment by GoAlexander** [comment]
Hm... Interesting... It is error of deployment system. I will deploy app again next time.

**Pull request merged**
